server_tokens off;

server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    charset utf-8;
    index index.php index.html;
    client_max_body_size 10M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    location ~ .*\.(html?|jpe?g|gif|png|css|js|ico|swf|inc) {
        expires 1d;  # キャッシュ期間は1日
        access_log off;
    }

}
